# Generated by Django 4.2.29 on 2026-03-24 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_is_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="delete_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
