# Generated by Django 4.2.29 on 2026-03-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_delete_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="reset_token",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
