# Generated by Django 4.2.29 on 2026-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_reset_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="delete_token",
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Фамилия"),
        ),
    ]
